### ISSUE TITLE
Asking for help: I'm puzzled about the .calib file

### ISSUE THREAD

**Issue by DelinQu** [kskin/UWbundle#1]
Hi [kskin](https://github.com/kskin/UWbundle/commits?author=kskin),
Thanks for your excellent repo! I'm a little puzzled about the file [CAL_prosilica_inverse.calib](https://github.com/kskin/UWbundle/blob/master/CAL_prosilica_inverse.calib). It must be a stereo camera calibration parameters, but I have no idea what the specific value means. Could you provide a solution to open it or every single parameter means? 

Thanks in advance!

**Comment by kskin** [comment]
Hi,

Thanks for reaching out. The calibration file follows the format listed
here under "stereo.calib": https://github.com/mattjr/structured

Thanks,
Katie

**Comment by DelinQu** [comment]
> 

Much appreciated! :D
